/* Generated by tools/sync-papers.mjs on 2026-09-24.
   Source of truth: rajveer-research/src/data/research.ts. Do not edit by hand:
   change the research site, then rerun the tool.

   Consumers: js/spiral.js (research spiral), js/trajectory.js (timeline),
   js/home.js (impact + marquee), and the static lists in index.html. */
window.PAPERS = [
  {
    "slug": "benchmark-accuracy-not-identified",
    "title": "Benchmark Accuracy Is Not an Identified Quantity",
    "short": "Benchmark Accuracy Is Not Identified",
    "status": "Under review",
    "venue": "",
    "kind": "review",
    "year": "2026",
    "href": "https://rajveer-research.vercel.app/research/benchmark-accuracy-not-identified/",
    "page": null,
    "color": "#3b82f6",
    "sub": "Most orderings on a published MATH-Hard leaderboard cannot be separated once the responses a scorer could not read are counted.",
    "tags": [
      "Benchmark Evaluation",
      "NLP · LLMs",
      "Deployment Shift"
    ]
  },
  {
    "slug": "subgroup-fairness-reversal",
    "title": "Higher AUC, Fewer Cases Flagged: Subgroup Fairness Metrics Can Reverse at the Decision Threshold in Federated Diabetes Screening",
    "short": "Higher AUC, Fewer Cases Flagged",
    "status": "Under review",
    "venue": "",
    "kind": "review",
    "year": "2026",
    "href": "https://rajveer-research.vercel.app/research/subgroup-fairness-reversal/",
    "page": null,
    "color": "#34d399",
    "sub": "Federated training narrows the White-Black AUC gap while a race-blind screening policy flags fewer Black respondents.",
    "tags": [
      "Fairness",
      "Healthcare AI",
      "Privacy · Federated",
      "Deployment Shift"
    ]
  },
  {
    "slug": "could-it-read-the-answer",
    "title": "Benchmarks Do Not Report Whether They Could Read the Answer",
    "short": "Could It Read the Answer?",
    "status": "Under review",
    "venue": "",
    "kind": "review",
    "year": "2026",
    "href": "https://rajveer-research.vercel.app/research/could-it-read-the-answer/",
    "page": null,
    "color": "#14b8a6",
    "sub": "Two answer extractors shipped in the same evaluation harness disagree by 88.5 points on the same 400 MMLU responses.",
    "tags": [
      "Benchmark Evaluation",
      "NLP · LLMs"
    ]
  },
  {
    "slug": "indiafinbench",
    "title": "Scoring-Rule Sensitivity in LLM Evaluation: Evidence from Indian Financial Regulatory Text",
    "short": "IndiaFinBench",
    "status": "Under review",
    "venue": "",
    "kind": "review",
    "year": "2026",
    "href": "https://rajveer-research.vercel.app/research/indiafinbench/",
    "page": "project-indiafinbench.html",
    "color": "#22d3ee",
    "sub": "Changing only the scoring rule reorders twelve LLMs on a new Indian financial-regulation benchmark, and no model keeps its rank.",
    "tags": [
      "Benchmark Evaluation",
      "NLP · LLMs",
      "Financial ML"
    ]
  },
  {
    "slug": "diabetes-external-validation",
    "title": "Comprehensive Evaluation of Machine Learning for Type 2 Diabetes Risk Prediction: Large-Scale External Validation and Fairness Analysis",
    "short": "Diabetes External Validation",
    "status": "Published",
    "venue": "IEEE Xplore (CIPHER-2026)",
    "kind": "published",
    "year": "2026",
    "href": "https://rajveer-research.vercel.app/research/diabetes-external-validation/",
    "page": null,
    "color": "#10b981",
    "sub": "Internally validated diabetes models lose discrimination on 1.28M external records, and adults over 60 lose the most.",
    "tags": [
      "Healthcare AI",
      "Fairness",
      "Deployment Shift"
    ]
  },
  {
    "slug": "trustshift",
    "title": "TrustShift: A Mechanism-Aware Audit of Machine-Learning Deployment Shift",
    "short": "TrustShift",
    "status": "Manuscript",
    "venue": "",
    "kind": "manuscript",
    "year": "2026",
    "href": "https://rajveer-research.vercel.app/research/trustshift/",
    "page": null,
    "color": "#f472b6",
    "sub": "Across four real deployment shifts, shift magnitude alone does not consistently explain which trustworthiness axis fails.",
    "tags": [
      "Deployment Shift",
      "Healthcare AI",
      "NLP · LLMs",
      "Network Security",
      "Fairness"
    ]
  },
  {
    "slug": "confidently-wrong",
    "title": "Confidently Wrong: Ranking Inversion in Cross-Network Denial-of-Service Detection",
    "short": "Confidently Wrong",
    "status": "Manuscript",
    "venue": "",
    "kind": "manuscript",
    "year": "2026",
    "href": "https://rajveer-research.vercel.app/research/confidently-wrong/",
    "page": null,
    "color": "#ef4444",
    "sub": "On a new network, DoS detectors do not decay toward chance: many pass through it and score attacks below benign traffic.",
    "tags": [
      "Network Security",
      "Deployment Shift"
    ]
  },
  {
    "slug": "scorer-partial-identification",
    "title": "Scorer-Induced Partial Identification of Benchmark Comparisons: An Audit-Design Approach",
    "short": "Auditing the Scorer",
    "status": "In preparation",
    "venue": "",
    "kind": "preparation",
    "year": "2026",
    "href": "https://rajveer-research.vercel.app/research/scorer-partial-identification/",
    "page": null,
    "color": "#ec4899",
    "sub": "Once a scorer’s error rate is audited rather than assumed, audit uncertainty outweighs sampling uncertainty in all 120 well-defined comparisons.",
    "tags": [
      "Benchmark Evaluation",
      "NLP · LLMs"
    ]
  },
  {
    "slug": "mortgage-disparities",
    "title": "Persistent Racial Disparities in U.S. Mortgage Approval: Evidence from 42 Million Applications, 2020-2024",
    "short": "Mortgage Disparities",
    "status": "Under review",
    "venue": "Journal of Housing Economics",
    "kind": "review",
    "year": "2026",
    "href": "https://rajveer-research.vercel.app/research/mortgage-disparities/",
    "page": null,
    "color": "#f59e0b",
    "sub": "The public-data Black-White mortgage approval gap at national scale: how large, where it lives, and how it responds to institutional boundaries.",
    "tags": [
      "Fairness",
      "Causal Inference"
    ]
  },
  {
    "slug": "who-bears-the-burden",
    "title": "Who Bears the Burden? Heterogeneous Racial Approval Differentials in U.S. Mortgage Lending: Causal Forest DML on 42 Million HMDA Applications",
    "short": "Who Bears the Burden?",
    "status": "Working paper",
    "venue": "SSRN",
    "kind": "working",
    "year": "2026",
    "href": "https://rajveer-research.vercel.app/research/who-bears-the-burden/",
    "page": null,
    "color": "#60a5fa",
    "sub": "Not whether an average penalty exists, but who bears it, and through which underwriting channel.",
    "tags": [
      "Causal Inference",
      "Fairness"
    ]
  },
  {
    "slug": "when-the-gate-stays-closed",
    "title": "When the Gate Stays Closed: Empirical Evidence of Near-Zero Cross-Sectional Predictability in Large-Cap NASDAQ Equities Using an IC-Gated Machine Learning Framework",
    "short": "The Gate Stays Closed",
    "status": "Working paper",
    "venue": "SSRN",
    "kind": "working",
    "year": "2026",
    "href": "https://rajveer-research.vercel.app/research/when-the-gate-stays-closed/",
    "page": null,
    "color": "#eab308",
    "sub": "A deployment gate for financial ML, and the discipline to report that it stayed closed.",
    "tags": [
      "Financial ML",
      "Deployment Shift"
    ]
  },
  {
    "slug": "text-genre-transfer-failure",
    "title": "Text Genre, Not Platform Identity, Predicts Transfer Failure in Mental Health Natural Language Processing: A Five-Axis Deployment Audit Across Five Corpora",
    "short": "Text Genre and Transfer Failure",
    "status": "Manuscript",
    "venue": "",
    "kind": "manuscript",
    "year": "2026",
    "href": "https://rajveer-research.vercel.app/research/text-genre-transfer-failure/",
    "page": null,
    "color": "#a855f7",
    "sub": "A five-axis pre-deployment audit of mental-health text classifiers moved across platforms and corpora.",
    "tags": [
      "NLP · LLMs",
      "Fairness",
      "Healthcare AI",
      "Deployment Shift"
    ]
  }
];
