// Writes sitemap.xml and llms.txt, and keeps the social / structured-data block in
// each indexable page's <head> in sync. Pages that carry a cross-domain canonical to
// the research site are deliberately left out of the sitemap: they exist only so old
// inbound links keep working.
//
// Usage: node tools/build-seo.mjs   (run after tools/sync-papers.mjs)

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const SITE = "https://rajveer-code.github.io";
const papersSrc = readFileSync(join(ROOT, "js/papers.js"), "utf8");
const PAPERS = JSON.parse(papersSrc.slice(papersSrc.indexOf("["), papersSrc.lastIndexOf("]") + 1));

// Indexable pages: the home page and the systems this site owns.
const PAGES = [
  { file: "index.html", url: `${SITE}/`, priority: "1.0", changefreq: "weekly", og: "assets/og/home.png", name: "Rajveer Singh Pall" },
  { file: "project-aria.html", url: `${SITE}/project-aria.html`, priority: "0.8", changefreq: "monthly", og: "assets/og/aria.png", name: "ARIA Assistant" },
  { file: "project-indiafinbench.html", url: `${SITE}/project-indiafinbench.html`, priority: "0.8", changefreq: "monthly", og: "assets/og/indiafinbench.png", name: "IndiaFinBench" },
  { file: "project-fairscope.html", url: `${SITE}/project-fairscope.html`, priority: "0.8", changefreq: "monthly", og: "assets/og/fairscope.png", name: "fairscope" },
  { file: "project-finsight.html", url: `${SITE}/project-finsight.html`, priority: "0.7", changefreq: "monthly", og: "assets/og/finsight.png", name: "FinSight" },
  { file: "project-finsight-web.html", url: `${SITE}/project-finsight-web.html`, priority: "0.7", changefreq: "monthly", og: "assets/og/finsight-web.png", name: "FinSight + Web" },
  { file: "project-serenespace.html", url: `${SITE}/project-serenespace.html`, priority: "0.7", changefreq: "monthly", og: "assets/og/serenespace.png", name: "SereneSpace" },
];

const today = new Date().toISOString().slice(0, 10);
const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
// Titles and descriptions are read back out of the HTML, so they are already escaped.
const attr = (s) =>
  esc(s.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"'));

// ---- sitemap.xml -------------------------------------------------------------
writeFileSync(
  join(ROOT, "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${PAGES.map(
  (p) =>
    `    <url><loc>${p.url}</loc><lastmod>${today}</lastmod><changefreq>${p.changefreq}</changefreq><priority>${p.priority}</priority></url>`,
).join("\n")}
</urlset>
`,
);

// ---- llms.txt ----------------------------------------------------------------
const systems = [
  ["ARIA Assistant", "project-aria.html", "Local-first voice agent: 16 tools, 7.1 GB VRAM, no cloud LLM calls."],
  ["IndiaFinBench", "project-indiafinbench.html", "406 expert-annotated questions over SEBI and RBI regulation, with a hybrid BM25 and FAISS retrieval stack."],
  ["fairscope", "project-fairscope.html", "Subgroup-stratified, calibration-aware fairness auditing on PyPI."],
  ["FinSight", "project-finsight.html", "Earnings-intelligence pipeline over 14,584 transcripts from 601 S&P 500 firms."],
  ["FinSight + Web", "project-finsight-web.html", "A scroll-driven WebGL monograph of the FinSight findings."],
  ["SereneSpace", "project-serenespace.html", "Anonymous student mental-health platform, top 50 of 250 at Smart India Hackathon 2025."],
];
writeFileSync(
  join(ROOT, "llms.txt"),
  [
    "# Rajveer Singh Pall",
    "",
    "> Machine-learning researcher and engineer. This site covers the systems: local-first agents, retrieval, fairness tooling and research pipelines. The papers live on the research site, which is the canonical source for their status and numbers.",
    "",
    "Statuses are stated exactly and never upgraded. Papers under double-blind review do not name their venue.",
    "",
    "## Systems",
    "",
    ...systems.map(([n, f, d]) => `- [${n}](${SITE}/${f}): ${d}`),
    "",
    "## Papers and manuscripts",
    "",
    ...PAPERS.map((p) => `- [${p.title}](${p.href}): ${p.venue ? p.venue + " · " : ""}${p.status}. ${p.sub}`),
    "",
    "## Elsewhere",
    "",
    "- [Research site](https://rajveer-research.vercel.app): the papers, in full",
    "- [GitHub](https://github.com/Rajveer-code)",
    "- [Google Scholar](https://scholar.google.com/citations?hl=en&user=47CvVCcAAAAJ)",
    "",
  ].join("\n"),
);

// ---- head block per indexable page -------------------------------------------
const START = "  <!-- seo:start (generated by tools/build-seo.mjs) -->";
const END = "  <!-- seo:end -->";

const itemList = {
  "@context": "https://schema.org",
  "@type": "ItemList",
  name: "Papers and manuscripts by Rajveer Singh Pall",
  numberOfItems: PAPERS.length,
  itemListElement: PAPERS.map((p, i) => ({
    "@type": "ListItem",
    position: i + 1,
    url: p.href,
    name: p.title,
  })),
};

const breadcrumbs = (p) => ({
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: `${SITE}/` },
    { "@type": "ListItem", position: 2, name: p.name, item: p.url },
  ],
});

for (const page of PAGES) {
  const path = join(ROOT, page.file);
  let html = readFileSync(path, "utf8");
  const title = html.match(/<title>([^<]*)<\/title>/)[1];
  const description = html.match(/<meta name="description" content="([^"]*)"/)[1];
  const ld = page.file === "index.html" ? itemList : breadcrumbs(page);

  const block = [
    START,
    `  <meta property="og:type" content="website">`,
    `  <meta property="og:site_name" content="Rajveer Singh Pall">`,
    `  <meta property="og:title" content="${attr(title)}">`,
    `  <meta property="og:description" content="${attr(description)}">`,
    `  <meta property="og:url" content="${page.url}">`,
    `  <meta property="og:image" content="${SITE}/${page.og}">`,
    `  <meta property="og:image:width" content="1200">`,
    `  <meta property="og:image:height" content="630">`,
    `  <meta property="og:image:alt" content="${esc(page.name)}, by Rajveer Singh Pall">`,
    `  <meta name="twitter:card" content="summary_large_image">`,
    `  <meta name="twitter:title" content="${attr(title)}">`,
    `  <meta name="twitter:description" content="${attr(description)}">`,
    `  <meta name="twitter:image" content="${SITE}/${page.og}">`,
    `  <script type="application/ld+json">${JSON.stringify(ld).replace(/</g, "\\u003c")}</script>`,
    END,
  ].join("\n");

  // Drop any previous generated block, and the hand-written og tags it replaces.
  const rx = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  html = html.replace(new RegExp(`${rx(START)}[\\s\\S]*?${rx(END)}\\n`, "g"), "");
  html = html
    .split("\n")
    .filter((l) => !/^\s*<meta property="og:(title|description|type|url|image|site_name)"/.test(l))
    .join("\n");
  html = html.replace("</head>", `${block}\n</head>`);
  writeFileSync(path, html);
}

console.log(`sitemap.xml: ${PAGES.length} URLs (stubs excluded)`);
console.log(`llms.txt: ${systems.length} systems, ${PAPERS.length} papers`);
console.log(`head block written into ${PAGES.length} pages`);
