// Regenerates js/papers.js from the research site's verified record.
//
// The research site (D:/Projects/rajveer-research/src/data/research.ts) is the only
// place a paper's status, title or one-line summary is decided. This tool copies that
// record into a plain script the portfolio's three renderers read, so a status can
// never drift between the homepage list, the spiral, the timeline and the marquee.
//
// Usage: node tools/sync-papers.mjs        (needs Node 22.18+ to import the .ts file)
//        RESEARCH_SRC=/other/path node tools/sync-papers.mjs

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const RESEARCH_SRC = process.env.RESEARCH_SRC ?? "D:/Projects/rajveer-research/src/data/research.ts";
const OUT = join(ROOT, "js/papers.js");
const SITE = "https://rajveer-research.vercel.app";

const { publications, THEME_LABELS } = await import(`file:///${RESEARCH_SRC.replace(/^\/+/, "")}`);

// Colours: keep each paper's existing hue where the portfolio already had one.
const COLOR = {
  trustshift: "#f472b6",
  "who-bears-the-burden": "#60a5fa",
  "mortgage-disparities": "#f59e0b",
  indiafinbench: "#22d3ee",
  "diabetes-external-validation": "#10b981",
  "subgroup-fairness-reversal": "#34d399",
  "when-the-gate-stays-closed": "#eab308",
  "text-genre-transfer-failure": "#a855f7",
  "benchmark-accuracy-not-identified": "#3b82f6",
  "could-it-read-the-answer": "#14b8a6",
  "confidently-wrong": "#ef4444",
  "scorer-partial-identification": "#ec4899",
};

// Only IndiaFinBench keeps a deep page here: it covers the retrieval system, not the
// paper's claims. Every other paper is owned by the research site.
const LOCAL_PAGE = { indiafinbench: "project-indiafinbench.html" };

const records = [...publications]
  .sort((a, b) => a.order - b.order)
  .map((p) => {
    // research.ts statuses read "Published · IEEE Xplore (CIPHER-2026)" or "Under review".
    const [status, ...rest] = p.status.split(" · ");
    const venue = rest.join(" · ");
    return {
      slug: p.slug,
      title: p.title,
      short: p.shortTitle,
      authors: p.authors,
      status,
      venue,
      kind: p.statusKind,
      year: p.year,
      href: `${SITE}/research/${p.slug}/`,
      page: LOCAL_PAGE[p.slug] ?? null,
      color: COLOR[p.slug] ?? "#c9a25a",
      sub: p.oneLiner,
      tags: p.themes.map((t) => THEME_LABELS[t]),
    };
  });

// Guard rails, checked at generation time so a bad record can never reach the site.
const VOCAB = ["Published", "Under review", "Working paper", "Manuscript", "In preparation"];
const NAMEABLE = new Set(["IEEE Xplore (CIPHER-2026)", "Journal of Housing Economics", "SSRN", ""]);
for (const r of records) {
  if (!VOCAB.includes(r.status)) throw new Error(`${r.slug}: status "${r.status}" outside the vocabulary`);
  if (!NAMEABLE.has(r.venue)) throw new Error(`${r.slug}: venue "${r.venue}" is not a public venue`);
  if (!r.title || !r.sub) throw new Error(`${r.slug}: missing title or summary`);
}

const banned = /0\.757|0\.700|40% (narrower|smaller)|21\.7|Applied Intelligence|CMPB|Computational Economics|Financial Services/i;
const hit = JSON.stringify(records).match(banned);
if (hit) throw new Error(`generated data contains a retired claim: ${hit[0]}`);

const body = `/* Generated by tools/sync-papers.mjs on ${new Date().toISOString().slice(0, 10)}.
   Source of truth: rajveer-research/src/data/research.ts. Do not edit by hand:
   change the research site, then rerun the tool.

   Consumers: js/spiral.js (research spiral), js/trajectory.js (timeline),
   js/home.js (impact + marquee), and the static lists in index.html. */
window.PAPERS = ${JSON.stringify(records, null, 2)};
`;

writeFileSync(OUT, body);
console.log(`js/papers.js: ${records.length} papers`);
for (const r of records) {
  console.log(`  ${r.status.padEnd(15)} ${(r.venue || "-").padEnd(30)} ${r.slug}${r.page ? "  [local page]" : ""}`);
}
